### ISSUE TITLE
运行样例失败

### ISSUE THREAD

**Issue by CodeWithACA** [RoboMaster/IntelligentUAVChampionshipBase#3]
按readme进行至

 ./run_kbctrl.sh
后没有新界面打开，终端不断弹出以下信息，且系统终端功能失灵，只能强制关机
[ERROR] [1696436762.721598819]: [PIDPositionController] Waiting for odometry!

使用roslaunch运行键盘控制也会如此

**Comment by ShihaoLuo** [comment]
确保 /airsim_node/drone_1/debug/pose_gt 话题可被正常接收。

**Comment by ShihaoLuo** [comment]
键盘控制占用了键盘监控事件，使用 esc 可以解除键盘占用， readme中有提及。
