### ISSUE TITLE
样例无法运行

### ISSUE THREAD

**Issue by Dionysus7777777** [RoboMaster/IntelligentUAVChampionshipBase#4]
在运行pos_ctrl时能够正常起飞但是之后保持不动并且在终端显示[error]:[PIDPositionController] waiting for ododetry并且key_ctrl也是起飞后无法通过键盘操控
![2023-12-12 08-54-50 的屏幕截图](https://github.com/RoboMaster/IntelligentUAVChampionshipBase/assets/144111054/2b15173f-295f-4f32-ae76-28d3a26b092e)
![2023-12-12 08-55-11 的屏幕截图](https://github.com/RoboMaster/IntelligentUAVChampionshipBase/assets/144111054/0cd5ed53-018e-4422-858c-838720006275)
![2023-12-12 08-57-08 的屏幕截图](https://github.com/RoboMaster/IntelligentUAVChampionshipBase/assets/144111054/4452c716-2b3d-4e79-b21b-22271b09b81a)

**Comment by ShihaoLuo** [comment]
#3  参考这个
